name: stroll_task1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  badges: ^3.1.2
#  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Thin.otf
          weight: 100
        - asset: assets/fonts/ProximaNova-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/ProximaNova-Semibold.otf
          weight: 600
        - asset: assets/fonts/ProximaNova-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/ProximaNova-Extrabold.otf
          weight: 800
        - asset: assets/fonts/ProximaNova-ExtraboldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/ProximaNova-Black.otf
          weight: 900
        - asset: assets/fonts/ProximaNova-BlackItalic.otf
          weight: 900
          style: italic

